"""SQLAlchemy / Python enums matching GraphQL schema."""
import enum


class UserRole(str, enum.Enum):
    USER = "USER"
    NOTARY = "NOTARY"
    ADMIN = "ADMIN"


class UserStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"


class Permission(str, enum.Enum):
    DOCUMENT_READ = "DOCUMENT_READ"
    DOCUMENT_CREATE = "DOCUMENT_CREATE"
    DOCUMENT_UPDATE = "DOCUMENT_UPDATE"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    ORDER_READ = "ORDER_READ"
    ORDER_CREATE = "ORDER_CREATE"
    APPOINTMENT_READ = "APPOINTMENT_READ"
    APPOINTMENT_CREATE = "APPOINTMENT_CREATE"
    APPOINTMENT_MANAGE = "APPOINTMENT_MANAGE"
    ADMIN_USERS = "ADMIN_USERS"
    ADMIN_SETTINGS = "ADMIN_SETTINGS"
    ADMIN_REPORTS = "ADMIN_REPORTS"
    ADMIN_APPLICATIONS = "ADMIN_APPLICATIONS"
    NOTARY_APPLY = "NOTARY_APPLY"
    NOTARY_PROFILE = "NOTARY_PROFILE"
    NOTARY_AVAILABILITY = "NOTARY_AVAILABILITY"
    ADDRESS_READ = "ADDRESS_READ"
    ADDRESS_CREATE = "ADDRESS_CREATE"
    ADDRESS_UPDATE = "ADDRESS_UPDATE"
    ADDRESS_DELETE = "ADDRESS_DELETE"


class DocumentStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    NOTARIZED = "NOTARIZED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class DocumentCategory(str, enum.Enum):
    PROPERTY = "PROPERTY"
    PERSONAL = "PERSONAL"
    BUSINESS = "BUSINESS"
    LEGAL = "LEGAL"
    RENT_LEASE = "RENT_LEASE"
    AFFIDAVITS = "AFFIDAVITS"
    MANAGING_BUSINESS = "MANAGING_BUSINESS"


class OrderType(str, enum.Enum):
    PHYSICAL_DELIVERY = "PHYSICAL_DELIVERY"
    VIDEO_CONSULTATION = "VIDEO_CONSULTATION"


class OrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    PAID = "PAID"
    PROCESSING = "PROCESSING"
    NOTARIZED = "NOTARIZED"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"


class AppointmentStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class DeliveryStatus(str, enum.Enum):
    PROCESSING = "PROCESSING"
    PRINTED_PACKED = "PRINTED_PACKED"
    IN_TRANSIT = "IN_TRANSIT"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"


class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class PaymentMethod(str, enum.Enum):
    CARD = "CARD"
    UPI = "UPI"
    NET_BANKING = "NET_BANKING"
    WALLET = "WALLET"


class NotaryApplicationStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DayOfWeek(str, enum.Enum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


class FAQCategory(str, enum.Enum):
    GENERAL = "GENERAL"
    DOCUMENTS = "DOCUMENTS"
    NOTARIZATION = "NOTARIZATION"
    PRICING = "PRICING"
    DELIVERY = "DELIVERY"
    ACCOUNT = "ACCOUNT"


class LoginMethod(str, enum.Enum):
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    GOOGLE = "GOOGLE"


class KycStatus(str, enum.Enum):
    NOT_SUBMITTED = "NOT_SUBMITTED"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
